MedicalSearch/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include(('medsearch.urls', 'medsearch'), namespace='medsearch')),
]

medsearch/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('ranking', views.ranking, name='ranking'),
]

medsearch/models.py
from django.db import models

# Create your models here.

medsearch/views.py
from django.shortcuts import render
from django.http import HttpResponse
from static.bsbi import BSBIIndex
from static.compression import VBEPostings
from static.letor import LETOR

def index(request):
    return render(request, "search.html")

def ranking(request):
    BSBI_instance = BSBIIndex(data_dir = 'static/collection', \
                          postings_encoding = VBEPostings, \
                          output_dir = 'static/index')
    LETOR_instance = LETOR(model_dir='static/model')

    query = request.GET['query']

    docs = []
    for (score, doc) in BSBI_instance.retrieve_bm25(query, k = 10):
        docs.append((doc, " ".join(BSBI_instance.docs[doc]), BSBI_instance.docs_real[doc]))
    
    sorted_did_scores = LETOR_instance.predict(query, docs)

    return render(request, "search.html", {"list":sorted_did_scores})

medsearch/templates/search.html
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Medical Search</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body class="bg-dark text-light">
    <div class="container mainpage">
        <div class="row align-items-center">
            <div class="col-md">
                <h1>Medical Search</h1>
            </div>
            <div class="col-md d-flex flex-column justify-content-center">
                <form action="{% url 'medsearch:ranking' %}" method="GET">
                    <div class="inner-form mt-3">
                        <div class="input-group">
                            <input name="query" type="text" class="form-control" placeholder="Enter query"
                                aria-label="Enter query" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="submit">Search</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <hr />
        <div class="row mt-4" style="margin-bottom: 70px;">
            {% if list %}
            {% for doc in list %}
            <h4>{{ doc.0 }}</h4>
            <p>{{ doc.2 }}</p>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <footer class="footer bg-light text-center text-lg-start text-dark">
        <div class="text-center p-3">
            © TP 4 Perolehan Informasi:
            <a class="text-dark">Vanessa Emily Agape</a>
        </div>
    </footer>
</body>

</html>